#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# Copyright (c) 2020-2021 FreeHackQuest Team <freehackquest@gmail.com>
"""This file was automatically generated by fhq-server
Version: v0.2.51
Date: 2023-01-03 17:03:28
"""
from freehackquest_libclient_py.freehackquest_client import FreeHackQuestClient
