#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# Copyright (c) 2020-2021 FreeHackQuest Team <freehackquest@gmail.com>
"""This file was automatically generated by fhq-server
Version: v0.2.39
Date: 11 Apr 2021
"""
from libfreehackquestclient.freehackquest_client import FreeHackQuestClient
