#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# Copyright (c) 2020 FreeHackQuest Team <freehackquest@gmail.com>
"""This file was automatically generated by fhq-server
Version: v0.2.36
Date: 14 Mar 2021
"""
from libfreehackquestclient.freehackquest_client import FreeHackQuestClient
